id: IF3C331C5
default_language: bo
source: ''
initial_creation_type: tmx
imported: 2022-12-14 15:20:47.509737+00:00
last_modified: 2022-12-14 15:20:47.509745+00:00
source_metadata:
  creationtool: InterText
  creationtoolversion: '1.0'
  datatype: PlainText
  segtype: block
  adminlang: en-us
  srclang: bo
  o-tmf: XML aligned text
  eft-text-id: UT22084-088-016
  eft-text-version: 1.1.11 2021
  title: Toh_522-The_Dharani_of_the_Tathagata_Jnanolka-v1
bases:
  24F4:
    source_metadata: null
    order: 1
    base_file: 24F4.txt
    statistics: null
copyright:
  status: Unknown
  notice: ''
